# Generated by Django 5.0.4 on 2025-02-21 07:42

from django.db import migrations

def set_age_groups(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')
    people = Person.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = "Child"
        elif person.age <= 17:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"
        person.save()

def reset_age_groups(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')
    for person in Person.objects.all():
        person.age_group = Person._meta.get_field('age_group').default
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person_alter_course_description'),
    ]

    operations = [migrations.RunPython(set_age_groups, reverse_code=reset_age_groups)]

