# Generated by Django 5.0.4 on 2025-02-21 11:29

from django.db import migrations


def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    smartphones = SmartphoneModel.objects.all()
    for smartphone in smartphones:
        smartphone.price = len(smartphone.brand) * 120
        smartphone.save()

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    smartphones = SmartphoneModel.objects.all()
    for smartphone in smartphones:
        if smartphone.price >= 750:
            smartphone.category = "Expensive"
        else:
            smartphone.category = "Cheap"
        smartphone.save()

def execute_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reset_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    smartphones = SmartphoneModel.objects.all()
    for smartphone in smartphones:
        smartphone.price = SmartphoneModel._meta.get_field('price').default
        smartphone.save()

def reset_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    smartphones = SmartphoneModel.objects.all()
    for smartphone in smartphones:
        smartphone.category = SmartphoneModel._meta.get_field('category').default
        smartphone.save()

def reset_price_and_category(apps, schema_editor):
    reset_price(apps, schema_editor)
    reset_category(apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [migrations.RunPython(execute_price_and_category, reverse_code=reset_price_and_category)]

