# Generated by Django 5.0.4 on 2025-02-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_subject_lecturer_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
