# Generated by Django 5.0.4 on 2025-03-22 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewModel',
            new_name='Review',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Education', 'Education')], default='Technology', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
