# Generated by Django 5.0.4 on 2025-03-24 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_astronaut_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{1,15}$')]),
        ),
    ]
