# Generated by Django 5.0.4 on 2025-03-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_mission_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='spacecraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_missions', to='main_app.spacecraft'),
        ),
    ]
