# Generated by Django 5.0.4 on 2025-03-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='is_rulling',
            new_name='is_ruling',
        ),
        migrations.AlterField(
            model_name='dragon',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragons', to='main_app.house'),
        ),
        migrations.AlterField(
            model_name='dragon',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='dragons',
            field=models.ManyToManyField(related_name='quests', to='main_app.dragon'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='main_app.house'),
        ),
    ]
