# Generated by Django 5.0.4 on 2025-02-21 07:54

from django.db import migrations

def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    for item in ItemModel.objects.all():
        if item.price <= 10:
            item.rarity = "Rare"
        elif 11 <= item.price <= 20:
            item.rarity = "Very Rare"
        elif 21 <= item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"

        item.save()

def reset_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    for item in ItemModel.objects.all():
        item.rarity = ItemModel._meta.get_field('rarity').default
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [migrations.RunPython(set_rarity, reverse_code=reset_rarity)]

