# Generated by Django 5.0.4 on 2025-02-21 18:01
from datetime import timedelta

from django.db import migrations

from main_app.models import StatusChoices


def update_warranty_and_delivery(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')
    orders = OrderModel.objects.all()
    for order in orders:
        if order.status ==  StatusChoices.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status ==  StatusChoices.COMPLETED:
            order.warranty = "24 months"
            order.save()
        else:
            order.delete()

def reverse_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [migrations.RunPython(update_warranty_and_delivery, reverse_code=reverse_update)]

